### PR TITLE
Pushing changes to master

### PR DESCRIPTION
**Pull request by mrumar01**

### CODE REVIEW

**Comment by mrumar01** [comment]
.

**Comment by KapaBaws** [comment]
The code is very well structured and meets the requirements of the assignment. Multiple error handling methods have been implemented to make sure the code runs smoothly. The code is very well commented throughout and explains the purpose of each class and method showing understanding of the code. The classes provided have been used as requested alongside the extra requirements and the debug. However, the code seems very long and I believe some parts of the code could be changed to make it shorter and more efficient.

**Comment by nitronjoe** [comment]
Die.cs:
There is good use of error handling through out.
Good naming conventions for object (formatted using the Style Guildlines).
Use of Roll()
There isn't much use of the other files.
Code is easy to read with use of comments aswell.
Not sure if the die is rolled 3 times as mentioned in the brief. (Appears to only roll once within the code).

**Comment by mrumar01** [comment]
After double checking the die is being use three times, what you see in the console is the sum only.

**Pull request merged**
